KokkosCore: Fixed build error in tile_subview() implementation.
This commit affects the templated constructor of
Kokkos::Impl::ViewAssignment<Impl::ViewTile, void, void>.  This
specialization handles assignment from a LayoutLeftTile View, to a
LayoutLeft View.  It takes the block coordinates of a tile, and returns
the tile.

For some reason, on my computer (Mac), with Clang 3.5, the constructor's
template parameters needed to be "unsigned long" instead of "unsigned",
in order for the tile_subview() unit test to compile.  This could be
different on 32-bit machines or with different compilers.

I have attached the build error message below, in case it illuminates
the issue.

Building CXX object packages/kokkos/core/unit_test/CMakeFiles/KokkosCore_UnitTest.dir/TestSerial.cpp.o
In file included from .../Trilinos/packages/kokkos/core/unit_test/TestSerial.cpp:48:
.../Trilinos/packages/kokkos/core/src/impl/Kokkos_ViewTileLeft.hpp:177:10: error: no matching constructor for initialization of
      'Impl::ViewAssignment<Impl::ViewTile, void, void>'
  (void) Impl::ViewAssignment< Impl::ViewTile , void , void >( dst , src , i_tile0 , i_tile1 );
         ^                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.../Trilinos/packages/kokkos/core/unit_test/TestTile.hpp:64:32: note: in instantiation of function template specialization
      'Kokkos::tile_subview<long, 1, 1, Kokkos::Serial, void>' requested here
      tile_type tile = Kokkos::tile_subview( m_array , itile , jtile );
                               ^
.../Trilinos/packages/kokkos/core/src/Kokkos_Serial.hpp:434:9: note: in instantiation of member function
      'TestTile::ReduceTileErrors<Kokkos::Serial, Kokkos::LayoutTileLeft<1, 1, true> >::operator()' requested here
        functor( i , update );
        ^
.../Trilinos/packages/kokkos/core/src/Kokkos_Parallel.hpp:325:10: note: in instantiation of function template specialization
      'Kokkos::Impl::ParallelReduce<TestTile::ReduceTileErrors<Kokkos::Serial, Kokkos::LayoutTileLeft<1, 1, true> >, Kokkos::RangePolicy<Kokkos::Serial, unsigned long, void,
      Kokkos::Serial> >::ParallelReduce<Kokkos::View<long, Kokkos::HostSpace, Kokkos::MemoryTraits<1>, void, Kokkos::Impl::ViewDefault>, Kokkos::RangePolicy<Kokkos::Serial,
      unsigned long, void, Kokkos::Serial> >' requested here
  (void) Impl::ParallelReduce< FunctorType, ExecPolicy >( functor , policy , result_view );
         ^
.../Trilinos/packages/kokkos/core/unit_test/TestTile.hpp:104:11: note: in instantiation of function template specialization
      'Kokkos::parallel_reduce<Kokkos::RangePolicy<Kokkos::Serial, unsigned long, void, Kokkos::Serial>, TestTile::ReduceTileErrors<Kokkos::Serial, Kokkos::LayoutTileLeft<1, 1,
      true> > >' requested here
  Kokkos::parallel_reduce( Kokkos::RangePolicy<Space,size_t>(0,tile_dim0*tile_dim1) , functor_type( array ) , error );
          ^
.../Trilinos/packages/kokkos/core/unit_test/TestSerial.cpp:275:13: note: in instantiation of function template specialization
      'TestTile::test<Kokkos::Serial, 1, 1>' requested here
  TestTile::test< Kokkos::Serial , 1 , 1 >( 1 , 1 );
            ^
.../Trilinos/packages/kokkos/core/src/impl/Kokkos_ViewTileLeft.hpp:144:3: note: candidate template ignored: substitution failure
      [with T = long]: deduced non-type template argument does not have the same type as the its corresponding template parameter ('unsigned long' vs 'unsigned int')
  ViewAssignment( View< T[N0][N1], LayoutLeft, A2, A3, Impl::ViewDefault > & dst
  ^
.../Trilinos/packages/kokkos/core/src/impl/Kokkos_ViewTileLeft.hpp:140:8: note: candidate constructor (the implicit copy constructor) not
      viable: requires 1 argument, but 4 were provided
struct ViewAssignment< ViewTile , void , void >
       ^
.../Trilinos/packages/kokkos/core/src/impl/Kokkos_ViewTileLeft.hpp:140:8: note: candidate constructor (the implicit move constructor) not
      viable: requires 1 argument, but 4 were provided