Changed a call from powf() to pow().  This was causing a failure during compilation on debian linux:
../../../../../packages/nox/src-loca/src/LOCA_Stepper.C:388: implicit declaration of function `int powf(...)'
gmake[5]: *** [libloca_a-LOCA_Stepper.o] Error 1