Sacado:  Add include of <cmath> in Sacado_MathFunctions.hpp for clang.
Sacado has not compiled with recent versions of clang (most notably the
default compiler on recent versions of Mac OS X) because of this error:

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:664:35:
error:
      no matching function for call to 'fabs'
      abs(double __x) _NOEXCEPT {return fabs(__x);}

Simone Rossi figured out that this can be fixed by adding an include of
<cmath> in Sacado_MathFunctions.hpp.  I tried this on Mountain Lion and
it does indeed appear to work, and also appears to not cause any
problems with GNU.