Fixing Sundance build error after Thyra::EpetraLinearOpBase refactoring.
I juste updated the class TSF::EpetraMatrix for the refactored
EpetraLinearOpBase interface.

Testing:
--------

There was a timed-out test for MPI_DEBUG and the build for SERIAL_RELEASE
failed.

The test Sundance_NitschePoisson2D_MPI_4 just takes too long to run and times
out at 3 minutes on my poor 3 year old linux machine.  This test took 45
seconds to run on our smoken fast machine trlinos-test2.  This is right up
there with some nasty Zoltan tests which take up to 85 seconds to run on
trilinos-test2.

The failed build for Sundance for SERIAL_RELEASE showed:

../../src-std-framework/libsundanceStdFwk.so: undefined reference to `Teuchos::RCP<Thyra::VectorSpaceBase<double> const> TSFExtended::productSpace<double>(Teuchos::Array<TSFExtended::Vector\
Space<double> > const&)'

I don't see how I could have caused that.

I am pushing.

=============================
Build/Test Cases Summary
=============================

Sat Apr  3 18:12:25 MDT 2010

Enabled Packages: Sundance
Enabled all Forward Packages

Build test results:
-------------------
0) MPI_DEBUG => FAILED: Trilinos/MPI_DEBUG: passed=81,notpassed=1 => Not ready for final commit/push! (0.0 min)
1) SERIAL_RELEASE => FAILED: Trilinos/SERIAL_RELEASE: build failed => Not ready for final commit/push! (0.0 min)

Local commits for this build/test group:
----------------------------------------
197396f Fixing Sundance build error after Thyra::EpetraLinearOpBase refactoring.

***
*** WARNING: The acceptance criteria for doing a commit/push has *not*
*** been met, but a commit/push is being forced anyway by --force-commit-push!
***