SUMMARY: Porting to gcc 4.1.2
BUGS: [???]

CHECKLIST:

1) Did you add any source or other files needed for building, testing,
   or documentation? No

2) Did you update or change the build system (other than just adding
   source files)? No

3) Did you do a cvs update *very* recently before rebuilding and
   retesting? Yes

4) If justified, did you type 'make partial-clean' and then rebuild all
   libraries and executables with 'make everything'? No, I just rebuilt
   but given the nature of the changes I think this is okay.

5) Did you rerun the test suite on at least the packages that you
   changed (rerunning the entire Trlinos test suite on all affected
   packages is *strongly* recommended)? Yes, but only serial debug
   but again given the nature of the changes this is pretty safe.

COMMENTS:

Here I am getting Belos, Anasazi, MOOCHO to port to gcc 4.1.2.  Code
like:

    catch (std::exception e) {
       ...
    }

is resulting in link errors that look like:

=============================================================================

GCRODREpetraExFile-GCRODREpetraExFile.o: In function `Belos::GCRODRSolMgr<double, Epetra_MultiVector, Epetra_Operator>::solve()':
/home/rabartl/PROJECTS/Trilinos.base/Trilinos/packages/belos/src/BelosGCRODRSolMgr.hpp:941: undefined reference to `__cxa_get_exception_ptr'
/home/rabartl/PROJECTS/Trilinos.base/Trilinos/packages/belos/src/BelosGCRODRSolMgr.hpp:950: undefined reference to `__cxa_get_exception_ptr'
/home/rabartl/PROJECTS/Trilinos.base/Trilinos/packages/belos/src/BelosGCRODRSolMgr.hpp:1322: undefined reference to `__cxa_get_exception_ptr'
/home/rabartl/PROJECTS/Trilinos.base/Trilinos/packages/belos/src/BelosGCRODRSolMgr.hpp:1332: undefined reference to `__cxa_get_exception_ptr'
collect2: ld returned 1 exit status

=============================================================================

I have no idea why this code is causing this link error.  While this
should be legal C++ code it does violate Item 73 "Throw by value,
catch by reference" in "C++ Coding Standards".  Therefore, I am just
fixing all of these catch clauses to catch by reference and the
problem goes away.

The change is trivial and super portable with is to just change from
catching by value to catching by reference as:

    catch (const std::exception &e) {
       ...
    }

That is all that I have done here.